### ISSUE TITLE
how to fix?

### ISSUE THREAD

**Issue by zufan-yp** [ravenred/Plopper#2]
└─# python3 main.py "/var/log/snort/snort.log.1615119153"                                                                                    1 ⨯
/var/log/snort/snort.log.1615119153
Traceback (most recent call last):
  File "/root/install/plopper/main.py", line 21, in <module>
    main()
  File "/root/install/plopper/main.py", line 13, in main
    snort_output_list = snort_parser.read_file(file_location)  # Reads log to parse
  File "/root/install/plopper/snort_parser.py", line 14, in read_file
    start_line = f.readlines()      # Reads in first line
  File "/usr/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd4 in position 0: invalid continuation byte

![image](https://user-images.githubusercontent.com/78656480/110244621-28b78280-7f92-11eb-9672-5778626522ba.png)

**Comment by qir4ni** [comment]
What is the log format that you use?
